version: '3'

services:

  app:
    build:
      context: node
    container_name: app
    networks:
      - nginx-network
    volumes:
      - ./node:/usr/src/app
    tty: true
    ports:
      - "3000:3000"
    depends_on:
      - db

  nginx:  
    container_name: nginx
    restart: always
    build:
      context: ./nginx
    ports:
      - "8080:80"
    networks:
      - nginx-network

  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    # Record modifications localy
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - nginx-network

networks:
  nginx-network:
    driver: bridge